if buffer_exists(buffer)
buffer_delete(buffer)
if part_system_exists(p_sys)
part_system_destroy(p_sys)
if part_type_exists(p_pix)
part_type_destroy(p_pix)
if sprite_exists(mysprite)
sprite_delete(mysprite)
if layer_exists(lay)
layer_destroy(lay)
if surface_exists(surf)
surface_free(surf)