draw_reset_color()
draw_rectangle_center_rotated(x,y,width,height,image_angle,true,2.5)
draw_set_colour(c_black)
draw_rectangle_center_rotated(x,y,width - 5,height - 5,image_angle) 
draw_reset_color()